# Generated by Django 4.2.7 on 2023-12-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_author', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.user')),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.message')),
            ],
        ),
    ]
